<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>SephiriaBuildOverlay.Core</AssemblyName>
    <RootNamespace>SephiriaBuildOverlay.Core</RootNamespace>
    <Version>0.1.18</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <EmbeddedResource Include="Catalog\catalog-1.0.33.json" />
    <EmbeddedResource Include="Catalog\costumes-1.0.33.json" />
    <Compile Include="..\SharedUpdates\*.cs" Link="Updates\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
